### ISSUE TITLE
cant see the 

### ISSUE THREAD

**Issue by tristian2** [OfficeDev/PnP-Partner-Pack#103]
Hi,

I am in Azure AD management, but I cant see Office 365 SharePoint Online in the "permissions to other applications".  I am following the steps in the manual setup guide.  Just after clicking the "Add Application" button.

any ideas?  

thanks

**Comment by PaoloPia** [comment]
Hi,
I'm sorry but I have no idea. I would try again using the manage.azure.com site. Please let us know if you find a solution. In the meantime I will close the issue, 'cause I don't think it is related to a bug of the project. Thanks.
