### ISSUE TITLE
Error stepping through Site creation: Internal Server Error - Relative Url length to long

### ISSUE THREAD

**Issue by petecuttriss** [OfficeDev/PnP-Partner-Pack#106]
I've found that you receive the error "Error stepping through Site creation: Internal Server Error", if your site collection relative url is too long (greater than 33 characters).   

The error is generated in the EnqueueProvisioningJob method of the SharePointProvisioningRepository.cs (within the Infrastructure project).  In the EnqueueProvisioningJob method, line 268, the listitem title field is set.  The title field no doubt has a 255 character limit which is exceeded if your site collection relative url is too long.

In my case I've put a [MaxLength(33)] attribute against the RelativeUrl property of the CreateSiteViewModel to stop this error occurring.   Another option would be trim the job.Title value to 255 characters.

Regards
Pete

**Comment by PaoloPia** [comment]
Thanks Pete,
We will take this into account as a fix for the current and for the next engine of the PnP Partner Pack.
