### ISSUE TITLE
OneColumnSideBar Wiki Page Layout

### ISSUE THREAD

**Issue by twimon** [OfficeDev/PnP-Partner-Pack#107]
The PageLayout OneColumnSideBar is no accepted in a provisioning template. 

> Apply-SPOProvisioningTemplate : The provided template is not valid!

The direct coding is possible and works fine.
> web.AddLayoutToWikiPage("SitePages", OfficeDevPnP.Core.WikiPageLayout.OneColumnSideBar, "Homepage.aspx");

**Comment by erwinvanhunen** [comment]
Hi!

I just checked the schema and the correct value to enter in the template is

OneColumnSidebar

(so with a lowercase 'b').

**Comment by twimon** [comment]
Thanks for you quick response.

Best Regards
Timon


Timon Waltz
Abteilung Informatik – Betrieb

HUK-COBURG
Bahnhofsplatz
96444 Coburg
Telefon:        09561 96-44586
Telefax:
E-Mail: Timon.Waltz@huk-coburg.de
Internet:       www.huk.de
________________________________
HUK-COBURG Haftpflicht-Unterstützungs-Kasse kraftfahrender Beamter Deutschlands a. G. in Coburg
Reg.-Gericht Coburg HRB 100; St.-Nr. 9212/101/00021
Sitz der Gesellschaft: Bahnhofsplatz, 96444 Coburg
Vorsitzender des Aufsichtsrats: Prof. Dr. Heinrich R. Schradin.
Vorstand: Dr. Wolfgang Weiler (Sprecher), Stefan Gronbach, Klaus-Jürgen Heitmann, Dr. Hans Olav Herøy, Sarah Rössler, Daniel Thomas (stv.).
________________________________
Diese Nachricht enthält vertrauliche und/oder rechtlich geschützte Informationen.
Wenn Sie nicht der richtige Adressat sind oder diese Nachricht irrtümlich erhalten haben,
informieren Sie bitte sofort den Absender und vernichten Sie diese Nachricht.
Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Nachricht ist nicht gestattet.

This information may contain confidential and/or privileged information.
If you are not the intended recipient (or have received this information in error) please notify the
sender immediately and destroy this information.
Any unauthorized copying, disclosure or distribution of the material in this information is strictly forbidden.
________________________________
Von: Erwin van Hunen [mailto:notifications@github.com]
Gesendet: Montag, 4. April 2016 17:17
An: OfficeDev/PnP-Partner-Pack <PnP-Partner-Pack@noreply.github.com>
Cc: Waltz, Timon <Timon.Waltz@huk-coburg.de>
Betreff: Re: [OfficeDev/PnP-Partner-Pack] OneColumnSideBar Wiki Page Layout (#107)


Hi!

I just checked the schema and the correct value to enter in the template is

OneColumnSidebar

(so with a lowercase 'b').

**Comment by twimon** [comment]
Thanks for you quick response!
