### ISSUE TITLE
supported site templates

### ISSUE THREAD

**Issue by AnassKartit** [OfficeDev/PnP-Partner-Pack#108]
Hi,
I tried creating meeting/community based templates but only team sites work , are they supported?
Thanks

**Comment by PaoloPia** [comment]
Hi,
the PnP Partner Pack uses the PnP Provisioning Engine, which is part of the SharePoint PnP Core library. There, we support the following base template types:
STS#0
BLOG#0
BDR#0
DEV#0
OFFILE#1
BICENTERSITE#0
SRCHCEN#0
BLANKINTERNETCONTAINER#0
ENTERWIKI#0
PROJECTSITE#0
COMMUNITY#0
COMMUNITYPORTAL#0
SRCHCENTERLITE#0
VISPRUS#0

Moreoveer, in SPO:
EHS#1
BLANKINTERNETCONTAINER#0"

While, in SP on-premises:
STS#1
BLANKINTERNET#0

However, most of the testing in the PnP Partner Pack have been done with Team Sites. Thus, if you find any possible issue, please let use know.

Thanks.
