### ISSUE TITLE
Not able to provision site collection by using site template xml file.

### ISSUE THREAD

**Issue by pak-kulkarni** [OfficeDev/PnP-Partner-Pack#113]
Hello Team,

I have completed the PnP partner pack set up by following the channel9 Video. Everything is working as expected. I have provisioned one site collection by using default blank template provided. Site got created. After that i added Discussion Board, Calendar, and Usefull Links webpart to home page of this site and Saved this site as template. I am trying to provision another site collection by using this template. Site is getting created but template is not applied. It is still taking blank template only. in We b Job logs also no errors reported. Please help if somebody faced the same kind of issue. Thanks in advance

**Comment by 2P2-Anthony** [comment]
@pak-kulkarni - have you solved this problem? I'm having issues deploying a Save As Template, but it's blowing up instead. Is there anything in your WebJobs logs that says something is going wrong with the deployment?

**Comment by PaoloPia** [comment]
Hi,
Sorry for the delayed answer. Are you still experiencing the issues? Do you have further details like the log of the webjob? Thanks.

**Comment by PaoloPia** [comment]
Hi,
Any news on this topic? Otherwise, I will close the issue. Thanks.

**Comment by PaoloPia** [comment]
I will close this one for lack of response. I assume it is ok, otherwise let me know and I will be more than welcome to re-open it. Thanks.
