### ISSUE TITLE
Create Site Collection :: Select a Template blank, no listing...

### ISSUE THREAD

**Issue by 2P2-Anthony** [OfficeDev/PnP-Partner-Pack#117]
Howdy...

I've published the Partner Pack Web Application as per the documentation, but I don't see a listing of Templates to select from to start the Auto-Provisioning Process. I believe I can communicate with SPO because when i go to Settings, I can see a list of Site Collections. And enable/disable Partner Pack on targeted Site Collections.

Any ideas why I can't see the Default Template List?

**Comment by 2P2-Anthony** [comment]
I've been able to create a new Site Template from an existing Site Collection (via Enable Partner Pack & Save site as Provisioning Template). And the new Template shows up, but the default Empty Site template does not. Nor does the Default Sub-Site Template show up when I click on the Create Subsite hijacked link within Site Settings.

Could this be a permissions issue with the account that created the Infrastructure Site Collection versus the Web App account that's looking for the info? The Web App successfully finds and injects the Partner Pack Override XML file, but can't seem to find the default site and sub-site templates.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using PnP. It could be a permission issue, but please double-check that the out of the box empty templates are in the infrastructural site collection. Thanks.

**Comment by 2P2-Anthony** [comment]
See attached image. This looks correct to me.

![pnp provisioning templates](https://cloud.githubusercontent.com/assets/6393228/15599662/a188b422-2399-11e6-8062-829d504ba05f.jpg)

**Comment by PaoloPia** [comment]
Please double-check the content-type under the  cover of each template type. That could be the issue. Please let me know. Thanks.

**Comment by 2P2-Anthony** [comment]
That was it. Thanks.

Wonder what went wrong with the install templates.

P.S. There are some updates I'd like to recommend to the install docs, do I just post an issue with the recommended corrections / adds?

**Comment by PaoloPia** [comment]
Great news. I'm happy that you fixed it. I will close this issue.
About the suggestions, please make a PR if you like. Thanks.
