### ISSUE TITLE
Settings :: Enable Partner Pack using temp AzureWebsites URL...

### ISSUE THREAD

**Issue by 2P2-Anthony** [OfficeDev/PnP-Partner-Pack#118]
During setup, the AzureWebSite URL I put into configure the Web App was found to be already taken, so I updated the URL to something unique and then re-ran all the config tools. The Pnp-Partner-Pack-Overrides was correctly updated with the new URL, but when I enable the Partner pack with an existing Site Collection it's embeding the original URL.

I've done a full solution search for the olde URL using several different variations from Full to Partial, and can't find any left overs. I've download the Web App version for comparision and it's setup correctly. And I've re-published the Web App several times. (I don't think I published the web app before I updated the AzureWebSiteUrl to the correct URL, but something is holding on to it somewhere.)

Thoughts on where to start looking to fix this?

**Comment by 2P2-Anthony** [comment]
Ok - fixed. Didn't update the templates on the Infrastructure SPO site after updating the URL.

**Comment by PaoloPia** [comment]
Cool! Great and thanks for letting us know.
