### ISSUE TITLE
Responsive UI package for the Office 365 SP sites

### ISSUE THREAD

**Issue by richardadc** [OfficeDev/PnP-Partner-Pack#119]
Hi,

I only need to implement the responsive feature for an SharePoint 2013 online site but even though the docs mention that the PnP package doesn't have to be installed to use this, there is no guide on how to actually achieve this.  

Can anyone assist with this?

Thanks

**Comment by PaoloPia** [comment]
Because you are targeting SP2013, please use this project instead: https://github.com/OfficeDev/PnP-Tools/tree/master/Solutions/SharePoint.UI.Responsive .Thanks. I will close this one.
