### ISSUE TITLE
Create Site Issues....

### ISSUE THREAD

**Issue by 2P2-Anthony** [OfficeDev/PnP-Partner-Pack#121]
I'm seeing two issues with creating new Site Collections using a template created via the Save Site as Template feature. We created a custom Site Collection, with a set of targeted Lists (News & Announcements, Calendar, Documents and Tasks),  and several "custom" Content Search Web Parts on the home page. We have Publishing turned on at both the site collection level and the site level. (Also some branding with custom logo and alternate css file.) Lastly, we enabled the Partner Pack Extensions for the custom Site Collection and successfully saved that as a Template.

However, when we attempt to use that template it fails on applying "Site Security" with errors like "The specified user Hierarchy Managers could not be found." or "The specified user Designers could not be found." I'm guessing that these "users" should be part of the Publishing Feature, which has not yet been enabled. Therefore shouldn't features run before Site Security?

If we rip out the whole Site Security Section, the update times out waiting for the Features Handler to finish. So far I have the time-out set for 10 minutes, and will be testing a longer time out (1 hour) out of curiosity.

While attempting to remote debug the web job (PartnerPack.ScheduledJob), it appears you can't remotely attach to a scheduled/on-demand web job. What is everyone else doing to debug ScheduledJob? Do you make it a continuous job in order to attach to it?

Has anyone successfully created a new site collection with a template saved from a Site Collection with publishing turned on? Or is the Best Practice to start empty and turn on all the features and upload any custom web parts separately, piece meal?

**Comment by PaoloPia** [comment]
Hi,
Sorry for the delayed answer. We are currently working on a PnP Partner Pack v.2 in which maybe we will be able to properly support publishing features. Right now, the v.1.1 of the PnP Partner Pack mainly supports the Team Site template. Thanks for your feedback.

**Comment by 2P2-Anthony** [comment]
Paolo...

With v2, will the new Document Library Look and Feel be supported? There appears to be two features "missing" with the new Document Libraries, alternate style sheets and the user injection spots. Do you know if these Features are going to be returned? And how the Partner Pack is going to deal with them missing if they are not coming back?

**Comment by PaoloPia** [comment]
Hi,
We are working on it and at the time of this message the only option we have is to revert the site back to the classic view. We will keep the community updated if there will be any news about this topic.
