### ISSUE TITLE
Site Storage Value Ignored...

### ISSUE THREAD

**Issue by 2P2-Anthony** [OfficeDev/PnP-Partner-Pack#123]
When we create new Site Collections, the Storage Maximum Level Value is being ignored. Doesn't matter what we enter it's only deploying the site with 1 GB of space. What is the expected units for this field? MBs? GBs?

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. Right now the StorageMaximumLevel property is in MB. In the upcoming v.2 of the PnP Partner Pack we will upgrade to GBs, accordingly to the new SPO settings.

**Comment by 2P2-Anthony** [comment]
Ah - that makes sense. Thanks.
