### ISSUE TITLE
Authentication error after web deploy step

### ISSUE THREAD

**Issue by amirkhanRC** [OfficeDev/PnP-Partner-Pack#127]
Hi there,
First of all thanks for an amazing initiative and a great resource.
I'm having trouble authenticating the app after completing all the steps in guide.

Error which clicking on the PnP app is
AADSTS70001: Application with identifier '"9d7aec0c-3af0-408e-92fb-4140281f4d79"' was not found in the directory <mydir>.onmicrosoft.com

Ive verified that the AppID mentioned in the error is infact correct and does exist as an AAD app in my 0365 tenant.
I've checked the app permissions especially the app and delegated permissions to other apps and it matches your guide.
also ensured that Enable Organizational Authentication is unchecked.

Any ideas or tips of what else to check?
Thanks is advance
Amir

**Comment by amirkhanRC** [comment]
Hi again,
managed to solve the issue by adding the actual cert thumbprint as the value for WEBSITE_LOAD_CERTIFICATES in the app settings of the web app (instead of *)

after that was able to access the PnP app however I got on error stating that the reply address didnt match.
fixed that by adding an "/" as was stated in your guide.
Now I'm able to load the PnP app and I see the welcome page. 
On the scheduled jobs next...
Thanks!

**Comment by PaoloPia** [comment]
Great! And thanks for using the PnP Partner Pack and for updating us. I will close this issue.
