### ISSUE TITLE
Search Configuration Apply Error

### ISSUE THREAD

**Issue by twimon** [OfficeDev/PnP-Partner-Pack#129]
When I am trying to apply search configuration I am getting an error. When I am using the same template with the powershell it is working fine.

> ServerException was caught
> The server was unable to process the request due to an internal error.
> For more information about the error, either turn on IncludeExceptionDetailInFaults
> (either from ServiceBehaviorAttribute or from the <serviceDebug> configuration behavior)
> on the server in order to send the exception information back to the client, or turn on
> tracing as per the Microsoft .NET Framework SDK documentation and inspect the server
> trace logs.

**Comment by PaoloPia** [comment]
Hi, can you share something more? Are working with a root site collection template or with a sub-site template? What kind of site template is at the basis of your target site? Thanks.

**Comment by twimon** [comment]
It is an Root Level Template with the Schema http://schemas.dev.office.com/PnP/2015/12/ProvisioningSchema and the Template is the STS#0 (Default of this Schema). I have the Standard pnp:SearchSettings and only under ResultTypes I have a Definition.

**Comment by PaoloPia** [comment]
Can you try the provisioning of your template using the provisioning engine within Visual Studio (using the CSOM package of SharePointPnP) just to be able to debug and see the issue? Moreover, in the upcoming August release of PnP there will be some changes in the search settings handler, together with support for the new 201605 schema. I would suggest to wait for the new release. From a PnP Partner Pack perspective, the new engine and schema will follow shortly (most likely in early September).

**Comment by bcage29** [comment]
@twimon FYI to apply the search schema you need to have a user context. App only context will not work.

**Comment by PaoloPia** [comment]
Hi,
Thanks for sharing I realized the issue and I updated the PnP Partern Pack v2 (which will be released pretty soon) accordingly. I will close this one.
