### ISSUE TITLE
Subsite Creation:  Site Description is not set 

### ISSUE THREAD

**Issue by spsguru** [OfficeDev/PnP-Partner-Pack#132]
With the Partner Pack, and creating sub sites within a site collection, we are seeing that the sub site's description is not getting set, even though it was entered in the create sub site form. I can see that the description does get included in the .job file, but the sub sites get created and everything is proper except for the description.

It seems as though this would be a straightforward thing, as Partner Pack is using the normal construct to create subwebs with CSOM, but I am baffled as to why it is failing to set the description Any ideas?

**Comment by PaoloPia** [comment]
Hi,
Thanks for submitting this issue. It is an intersting one, because we set the description in code. I will dig into it and let you know. Thanks.

**Comment by spsguru** [comment]
Any update on this? Also, any update on PartnerPack 2.0? :->

**Comment by PaoloPia** [comment]
Hi,
I found the bug and I fixed it in the PnP Partner Pack v.2, which will be release the next week (there will be a demo about it in the upcoming PnP Monthly call on Tuesday). Thus, I will close this issue. Thanks for your contribution.

**Comment by spsguru** [comment]
Thanks Paolo, as always, excellent work!
