### ISSUE TITLE
Access denied. You do not have permission to perform this action or access this resource.

### ISSUE THREAD

**Issue by lokeshsharma47** [OfficeDev/PnP-Partner-Pack#133]
I am able to create site collection and sub site by provisioning framework using Apponly permission.

but when it calls this code, i am getting below error
Access denied. You do not have permission to perform this action or access this resource.
 web.ApplyProvisioningTemplate(template, ptai);

I have applied Tenant level permission to app, so i am able to create site collection as well.

Permission applied to App is as per below:
<AppPermissionRequests>
    <AppPermissionRequest Scope="http://sharepoint/content/tenant" 
                          Right="FullControl" />
</AppPermissionRequests>

Let me know where i am missing.

**Comment by PaoloPia** [comment]
Hi,
Could you please give a little bit more of context? Where do you call the ApplyProvisioningTemplate method? It is code coming from the PnP Partner Pack (reference file and line, if that is the case) or is it your custom code somewhere else? Or do you have a stacktrace to share? Thanks.

**Comment by lokeshsharma47** [comment]
Yes, I am using complete code in windows service, so i have not customised
a single line just changed web.config and using clied id and client secret
of app to make connection with sharepoint online.

**Comment by lokeshsharma47** [comment]
Hi 

I am using  SubSiteProvisioningJobHandler.cs class and below method to create sub site and provision sub site.

  private void CreateSubSite(SubSiteProvisioningJob job)
        {
            // Determine the reference URLs and relative paths
            String subSiteUrl = job.RelativeUrl;
            String siteCollectionUrl = PnPPartnerPackUtilities.GetSiteCollectionRootUrl(job.ParentSiteUrl);
            String parentSiteUrl = job.ParentSiteUrl;

            Console.WriteLine("Creating Site \"{0}\" as child Site of \"{1}\".", subSiteUrl, parentSiteUrl);

            using (ClientContext context = PnPPartnerPackContextProvider.GetAppOnlyClientContext(parentSiteUrl))
            {
                // Get a reference to the parent Web
                Web parentWeb = context.Web;

                // Create the new sub site as a new child Web
                WebCreationInformation newWeb = new WebCreationInformation();
                newWeb.Description = job.Description;
                newWeb.Language = job.Language;
                newWeb.Title = job.SiteTitle;
                newWeb.Url = subSiteUrl;
                newWeb.UseSamePermissionsAsParentSite = job.InheritPermissions;
                newWeb.WebTemplate = "STS#0";

                Web web = parentWeb.Webs.Add(newWeb);
                context.ExecuteQueryRetry();

                Console.WriteLine("Site \"{0}\" created.", subSiteUrl);

                // Apply the Provisioning Template
                Console.WriteLine("Applying Provisioning Template \"{0}\" to site.", 
                    job.ProvisioningTemplateUrl);

                // Determine the reference URLs and file names
                String templatesSiteUrl = job.ProvisioningTemplateUrl.Substring(0,
                    job.ProvisioningTemplateUrl.IndexOf(PnPPartnerPackConstants.PnPProvisioningTemplates));
                String templateFileName = job.ProvisioningTemplateUrl.Substring(job.ProvisioningTemplateUrl.LastIndexOf("/") + 1);

                // Configure the XML file system provider
                XMLTemplateProvider provider =
                    new XMLSharePointTemplateProvider(context, templatesSiteUrl,
                        PnPPartnerPackConstants.PnPProvisioningTemplates);

                // Load the template from the XML stored copy
                ProvisioningTemplate template = provider.GetTemplate(templateFileName);
                template.Connector = provider.Connector;

                // We do intentionally remove taxonomies, which are not supported in the AppOnly Authorization model
                // For further details, see the PnP Partner Pack documentation 
                ProvisioningTemplateApplyingInformation ptai =
                    new ProvisioningTemplateApplyingInformation();
                ptai.HandlersToProcess ^=
                    OfficeDevPnP.Core.Framework.Provisioning.Model.Handlers.TermGroups;

                // Configure template parameters
                foreach (var key in template.Parameters.Keys)
                {
                    if (job.TemplateParameters.ContainsKey(key))
                    {
                        template.Parameters[key] = job.TemplateParameters[key];
                    }
                }

                // Apply the template to the target site
                web.ApplyProvisioningTemplate(template, ptai);

                Console.WriteLine("Applyed Provisioning Template \"{0}\" to site.",
                    job.ProvisioningTemplateUrl);
            }
        }

**Comment by lokeshsharma47** [comment]
Any update on above issue, i am still facing the issue.

**Comment by PaoloPia** [comment]
Hi,
Unfortunately I don't have any update for you. I would double-check the permissions for the app in Azure AD. In fact, the code that raises the issue, usually works properly.

**Comment by PaoloPia** [comment]
Hi,
Any news about this topic? Have you double-checked the permissions for the app in Azure AD? Thanks.

**Comment by lokeshsharma47** [comment]
Hi,
It's working fine with azure AD now.

Thanks

On Aug 27, 2016 12:51 PM, "Paolo Pialorsi" <notifications@github.com> wrote:

Hi,
Any news about this topic? Have you double-checked the permissions for the
app in Azure AD? Thanks.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OfficeDev/PnP-Partner-Pack/issues/133#issuecomment-242901735>,
or mute the thread

**Comment by PaoloPia** [comment]
Thanks for the update. I will close this issue.
