### ISSUE TITLE
App only permissions 

### ISSUE THREAD

**Issue by StaffanNelemans** [OfficeDev/PnP-Partner-Pack#134]
Since the introduction of  Application permissions in Azure AD (Read and write managed metadata) see Manual-Setup-Guide.md, it is possible to create termgroups. 

Should the OfficeDevPnP.Core.Framework.Provisioning.Model.Handlers.TermGroups still be excluded or can this Handler now be used? 

If it can be used the "Architecture-and-Implementation.md" -> "Taxonomies Support"-section should be revised.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately, even if there are permission settings in Azure AD, the capability is not yet supported on the SPO side, so we still need to exclude the TermGroups handler. I will close this issue. Thanks.
