### ISSUE TITLE
Links return to https://pnp-partner-pack.azurewebsites.net

### ISSUE THREAD

**Issue by jjcollins53** [OfficeDev/PnP-Partner-Pack#136]
The "Save site as Provisioning Template" link on the Site Settings page and the "new subsite" link on the Site Contents page redirect to wrong Azure website (https://pnp-partner-pack.azurewebsites.net) In my case should be https://ptcpnppartnerpack.azurewebsites.net. Causes 401 Unauthorized error.

**Comment by PaoloPia** [comment]
Hi,
During the setup process of the PnP Partner Pack you have to provide the AzureWebSiteUrl parameter to the Provision-InfrastructureSiteArtifacts.ps1 script. The parameter configures the proper URL for the Azure Web Site. You can see more details here in the setup guide: https://github.com/OfficeDev/PnP-Partner-Pack/blob/master/Documentation/Manual-Setup-Guide.md#infrastructural-site-collection-provisioning

**Comment by jjcollins53** [comment]
Hi Paolo,
I was unable to run the Provision-InfrastructureSiteArtifacts.ps1 script successfully, so I ran the individual Apply-SPOProvisioningTemplate commands per the manual instructions. Because of this, the AzureWebSiteUrl never got properly set as well as setting the correct content types on the template xml file. All is well now. Thanks for your quick response!
