### ISSUE TITLE
Custom Nav Bar and Footer not showing on new site collections.

### ISSUE THREAD

**Issue by jjcollins53** [OfficeDev/PnP-Partner-Pack#137]
I'm not seeing the custom nav bar and footer on newly created site collection sites. What needs to be done for these to appear?

**Comment by PaoloPia** [comment]
I would suggest you to double-check with F12 if the JS and CSS files related to the custom nav bar are downloaded. One issue could be a wrong URL for the JS/CSS files, or a missing custom action.

**Comment by PaoloPia** [comment]
Hi,
Any news about this topic? Otherwise, I will close the issue. Thanks.

**Comment by PaoloPia** [comment]
I will close this one for lack of response. I assume it is ok, otherwise let me know and I will be more than welcome to re-open it. Thanks.
