### ISSUE TITLE
Blank Site collection

### ISSUE THREAD

**Issue by rikhullar** [OfficeDev/PnP-Partner-Pack#143]
I have setup PnP partner pack on O365 developer license and created site collections.
All works fine the jobs are completed successfully and the site collection are provisioned. But whenever i access the site collection I see  blank site (means a total blank page). Can anyone let me know what could be the issue here?

**Comment by rikhullar** [comment]
I can go to settings and site content pages. But "Site Pages" library is blank ( just a blank page).

**Comment by Travis-Constellation** [comment]
Before you create the Infrastructure site, open the files at OfficeDevPnP.PartnerPack.SiteProvisioning\Templates\PnP-Empty-Site.xml and PnP-Empty-Sub-Site.xml.  You will see a line in the file like: <pnp:RegionalSettings AdjustHijriDays="0" AlternateCalendarType="None" CalendarType="None" Collation="25" FirstDayOfWeek="Sunday" FirstWeekOfYear="0" LocaleId="1033" ShowWeeks="false" Time24="false" TimeZone="13" WorkDayEndHour="5:00PM" WorkDays="62" WorkDayStartHour="8:00AM" />

Either remove/comment out the line or change CalendarType to Gregorian before creating the Infrastructure site collection.

If you have already created the Infrastructure Site collection edit the same two files in the PnPProvisioningTemplates library of the Infrastrucutre Site.  You can then create sites properly.

**Comment by rikhullar** [comment]
Thanks for a quick reply!
That resolved the issue for me.
