### ISSUE TITLE
New subsite pnp templates not available

### ISSUE THREAD

**Issue by ajhstn** [OfficeDev/PnP-Partner-Pack#147]
I have enabled the pnp partner pack to me existing site collections.  When i create a new subsite, i do not get the new pnp site templates, i just see the regular old new subsite form.

**Comment by PaoloPia** [comment]
Are you using the modern UI of SharePoint Online? If that is the case, you will need to upgrade to the PnP Partner Pack v.2, which will be released next week. In the meantime, you can revert to the SharePoint classic UI.

**Comment by PaoloPia** [comment]
We released the PnP Partner Pack v.2.0, where we support modern UI for subsite creation. I will close this issue. Please give a chance to the new release, and in case of any further issue let us know. Thanks.
