### ISSUE TITLE
Documentation: Architecture diagrams available?

### ISSUE THREAD

**Issue by amirkhanRC** [OfficeDev/PnP-Partner-Pack#157]
Hi Paolo,
Wondering if you have a architecture diagram portraying the various Azure components along with the process and information flow between o365 and the Partner pack solution?

Amir

**Comment by VesaJuvonen** [comment]
Hi @amirkhanRC,
we do have following presentation, which was used with the PnP Partner Pack 2.0 webcast recording available from YouTube at - https://www.youtube.com/watch?v=kittBIbTMRg. 

Here's the slides for this - https://docs.com/OfficeDevPnP/6147/pnp-web-cast-introduction-to-partner-pack-v2.

Is there something other what you'd be looking for?

**Comment by VesaJuvonen** [comment]
No response for 3 weeks, so closing the issue. Good feedback though.
