### ISSUE TITLE
Template Error on Create Site Collection

### ISSUE THREAD

**Issue by sscanl01** [OfficeDev/PnP-Partner-Pack#173]
After installing the PnP Partner Pack I am able to access the Azure site, however when I click on Create Site Collection I receive an error which says "Error searching for templates: Internal Server Error"
![pnppartner pack template error](https://cloud.githubusercontent.com/assets/23316462/20188514/e914f656-a770-11e6-88c5-50567bd49563.PNG)
![pnppartner pack template error]
Not sure what I have missed from the instructions, any help would be appreciated.

**Comment by sscanl01** [comment]
All is now working, I downloaded the files again and ran through the instructions possible issue previously when using visual studio but this time round all worked.

**Comment by jansenbe** [comment]
Can you show the TemplatesProviders node from your web.config file of the SiteProvisioning project. This should look like below, there's no need to adjust the gallery url:

```XML
    <TemplatesProviders>
      <TemplatesProvider name="TenantGlobal" enabled="true" type="OfficeDevPnP.PartnerPack.Infrastructure.TemplatesProviders.SharePointGlobalTemplatesProvider, OfficeDevPnP.PartnerPack.Infrastructure" />
      <TemplatesProvider name="SiteCollectionLocal" enabled="true" type="OfficeDevPnP.PartnerPack.Infrastructure.TemplatesProviders.SharePointLocalTemplatesProvider, OfficeDevPnP.PartnerPack.Infrastructure" />
      <TemplatesProvider name="TemplatesGallery" enabled="true" type="OfficeDevPnP.PartnerPack.Infrastructure.TemplatesProviders.PnPTemplatesGalleryProvider, OfficeDevPnP.PartnerPack.Infrastructure">
        <Configuration>
          <!--<gallery url="http://localhost:5039/" />-->
          <gallery url="https://pnp-templates-gallery-dev.azurewebsites.net/" />
        </Configuration>
      </TemplatesProvider>
    </TemplatesProviders>
```

**Comment by sscanl01** [comment]
Hi Bert,

Thanks for your response on this, I did manage to resolve the issue by downloading a fresh copy of the files and publishing those but for your reference here is the part of the web config file I used previously before download a fresh copy.

<TemplatesProviders>
      <TemplatesProvider name="TenantGlobal" enabled="true" type="OfficeDevPnP.PartnerPack.Infrastructure.TemplatesProviders.SharePointGlobalTemplatesProvider, OfficeDevPnP.PartnerPack.Infrastructure" />
      <TemplatesProvider name="SiteCollectionLocal" enabled="true" type="OfficeDevPnP.PartnerPack.Infrastructure.TemplatesProviders.SharePointLocalTemplatesProvider, OfficeDevPnP.PartnerPack.Infrastructure" />
      <TemplatesProvider name="TemplatesGallery" enabled="true" type="OfficeDevPnP.PartnerPack.Infrastructure.TemplatesProviders.PnPTemplatesGalleryProvider, OfficeDevPnP.PartnerPack.Infrastructure">
        <Configuration>
          
          <gallery url="https://pnp-templates-gallery-dev.azurewebsites.net/" />
        </Configuration>
      </TemplatesProvider>

Regards,


Shaun Scanlon
Global Senior SharePoint Administrator
Dentsu Aegis Network
EMail: Shaun.Scanlon@dentsuaegis.com
Web: http://www.dentsuaegisnetwork.com
Tel: +44 20 3535 8219
Twitter: @dentsuaegis
Dentsu Aegis Network

Dentsu Aegis Network Ltd is registered in England No.1403668 Registered office: 10 Triton Street, Regents Place, London, NW1 3BF

The content of this email and any attachments are private and confidential. If you are not the intended recipient(s) or have otherwise received this email in error, please delete the email and inform the sender as soon as possible. This email may not be disclosed, used or copied by anyone other than the intended recipient(s). Any opinions, statements or comments contained in this email are not necessarily those of Dentsu Aegis Network Ltd. If you wish clarification of any matter, please request confirmation in writing.

We take precautions to minimise the risk of this email containing a software virus but you should use virus checking software.
