### ISSUE TITLE
Newtonsoft dll error while installing the Templates

### ISSUE THREAD

**Issue by rajeshvartak** [OfficeDev/PnP-Partner-Pack#55]
Hi,

I am getting the following error on running the power shell command let for  Provisioning the template.

PowerShell Command
Apply-SPOProvisioningTemplate -Path "[Partner-Pack-Source-Code-Folder]\OfficeDevPnP.PartnerPack.SiteProvisioning\OfficeDevPnP.PartnerPack.SiteProvisioning\Templates\Infrastructure\PnP-Partner-Pack-Infrastructure-Jobs.xml"

ERROR
Apply-SPOProvisioningTemplate : Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral,
PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

Has anyone else encountered the same issue ? 
Thanks in advance.
Rajesh

**Comment by PaoloPia** [comment]
Please, be sure to have the latest release of the PnP PowerShell cmdlets, which are available here: https://github.com/OfficeDev/PnP-PowerShell/tree/master/Binaries 

Thanks,
Paolo

**Comment by rajeshvartak** [comment]
Hi Paolo,

I tried doing this but still the same error...
I tried updating the Newtonsoft dll's to the latest version i.e. 7.0.0.0 but i still get the same error. I couldn't find any reference to 6.0.0.0 version of Newtonsoft anywhere .

Am i missing something here ?

Thanks,
Rajesh

**Comment by rajeshvartak** [comment]
So...I updated nuget package for all projects...re-installed PnP Powershell commandlets...didn't work

Closed everything...restarted...bingo....all good...

Rajesh
