### ISSUE TITLE
Batch creation of site collections

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/PnP-Partner-Pack#56]
Demonstration of batch creation of site collections based on csv file, which is read and then messages for site collection creation are added to Azure storage queue for creation. 

Alternative model for site collection creation.

**Comment by PaoloPia** [comment]
It is now implemented in v2, using an XML file for the batch list and the classic PnP Partner Pack async engine to process the sites creation asynchronously. I will close this one.
