### ISSUE TITLE
Nuget will not pull various dependencies

### ISSUE THREAD

**Issue by pdemro** [OfficeDev/PnP-Partner-Pack#72]
This almost seems like an issue with Nuget, but I'm not sure here.  On initial clone & build attemp Nuget fails to download the following packages:

Microsoft.Net.Compilers 1.0.0
WindowsAzure.Storage 6.0.0
System.Spatial 5.6.3

Should these dependencies be updated in the project?

**Comment by PaoloPia** [comment]
Maybe ... btw, by the next monthly release we will probably have some upcoming updates. Thus, the package will be updated anyhow. Thanks for letting us know.

**Comment by PaoloPia** [comment]
Hi, I've just updated all the NuGet packages in the PnP Partner Pack and by the next monthly release, you will find them updated in the master branch, as well. I will close this issue. Thanks again for your support.
