### ISSUE TITLE
Doc update: explain what the minimum version of the PnP PS cmdlets is that you need

### ISSUE THREAD

**Issue by jansenbe** [OfficeDev/PnP-Partner-Pack#78]
The templates used during setup require a PS version that understands the schema of the templates (201512 in this case). connect-sponline -url blabla -verbose outputs the current version...can be used to verify if the version is "high" enough

**Comment by PaoloPia** [comment]
Done.

**Comment by jansenbe** [comment]
Thx Paolo!
