### ISSUE TITLE
Doc update: provide some more context on deploying the Azure web site 

### ISSUE THREAD

**Issue by jansenbe** [OfficeDev/PnP-Partner-Pack#79]
I got a strange auth exception because i forgot to uncheck the "Enable Organizational Authentication" checkbox...

Second thing is that ApplicationDBContext got prepopulated as I already deployed apps using a SQL Azure database in the past...this value should be cleaned...this will not cause problems, but better avoid the confusion

**Comment by PaoloPia** [comment]
Done.

**Comment by jansenbe** [comment]
Thx Paolo!
