### ISSUE TITLE
Remove code related to caching tokens

### ISSUE THREAD

**Issue by jansenbe** [OfficeDev/PnP-Partner-Pack#80]
We're not using this code, so best to get rid of it to avoid confusion

**Comment by PaoloPia** [comment]
Actually, I added a working copy and I'm supporting the user's picture in the upper right corner of the Office 365 SuiteBar ... to show how to play with the Microsoft Graph.

**Comment by jansenbe** [comment]
so does this mean one also needs SQL Azure to host the partner pack, for hosting the ADAL token cache database?
