### ISSUE TITLE
Doc update: order of content in section "Infrastructural Site Collection provisioning"

### ISSUE THREAD

**Issue by jansenbe** [OfficeDev/PnP-Partner-Pack#81]
We've a cool script that does most of the work...but we only tell that at the end of the section...by then folks already followed the manual steps. Small thing, but will help improve the experience. Actually I'm wondering if even should explain the manual steps...as they're not complete.

**Comment by tmech** [comment]
I have the same feedback. Structure the doc in one way that leads to success. The scripts seem to be the way that's best aligned with the goal of getting a partner up and running quickly. The manual steps are interesting for troubleshooting if something goes wrong with the script (if they are indeed complete) but could be broken out into a separate doc.

**Comment by PaoloPia** [comment]
Done. Thanks for the feedback.

**Comment by jansenbe** [comment]
Thx Paolo!
