### ISSUE TITLE
Doc update: order of content in section "Azure Web App provisioning and configuration"

### ISSUE THREAD

**Issue by jansenbe** [OfficeDev/PnP-Partner-Pack#82]
Start with outlining that we've a script that can do the setup before telling what needs to be done.

**Comment by tmech** [comment]
That has bitten me, too. I like the idea from #81 of focusing on the quickest path to success in this doc and move the manual steps to a separate doc for reference/troubleshooting/ideas for further automating the process.

**Comment by PaoloPia** [comment]
Done. Thanks for the feedback.

**Comment by jansenbe** [comment]
Thx Paolo!
