### ISSUE TITLE
No way back to Site Collection after clicking "Save site as a Provisioning Template"

### ISSUE THREAD

**Issue by petecuttriss** [OfficeDev/PnP-Partner-Pack#83]
Thanks for this great resource.

Once you click "Save site as a Provisioning Template", complete the form and click save, you aren't given any means to get back to the "Site Settings" page of the site collection/site from where you came.

**Comment by jansenbe** [comment]
Hi Pete,

That's indeed something we should add in an upcoming release

**Comment by PaoloPia** [comment]
Hi, 
Thanks for your feedback. We have a "back" button in the UI, since few months ago. However, we are working on the PnP Partner Pack v.2 where you will find much more improvements from a UI/UX perspective.
