### ISSUE TITLE
"File Not Found" when provisioning a site that has a composed look

### ISSUE THREAD

**Issue by petecuttriss** [OfficeDev/PnP-Partner-Pack#85]
Hi, I've been testing the PnP Partner Pack provisioning process.   I've created a simply site collection template which simply provisions a team site with a custom logo and composed look.  The composed look only contains a ColorFile (I've attached the associated template).

When I use the template to provision a new site collection, I receive a "File Not Found" error when the engine attempts to apply the template.   I've managed to debug the associated ScheduledJob and I've found that the issue occurs with the token replacement, in which the token {sitecollection} and {themecatalog} get replaced with an empty string.   When I traced it further I found that call to Web.Context.GetSiteCollectionContext (ThemeCatalogToken.cs) actually returned to the tenant admin site collection context (https://<mytenant>-admin.sharepoint.com)... rather than the context of the newly created site collection.   Because of this the {themecatalog} token simply came back as /_catalogs/theme... rather than /<sitecollection>/_catalogs/theme.   I'll try and debug it further to see why it's getting the tenant admin context.

[template-minimal.txt](https://github.com/OfficeDev/PnP-Partner-Pack/files/104299/template-minimal.txt)

**Comment by petecuttriss** [comment]
Further to this, the problem seems to be in the SiteCollectionProvisioningJobHandler.cs.   For some reason the adminContext (line 36) which wraps the call to web.ApplyProvisioningTemplate, then in turn passes through the tenant admin context.   I've tried moving the repositoryContext using statement out of the adminContext using statement, and then adding a separate call to GetAppOnlyClientContent prior to the web.ApplyProvisioningTemplate and it now works correctly and the tokens are correctly replaced by the core framework.   Attached is my updated SiteCollectionProvisioningJobHandler.cs version from the Infrastructure project. 
[SiteCollectionProvisioningJobHandler.txt](https://github.com/OfficeDev/PnP-Partner-Pack/files/104412/SiteCollectionProvisioningJobHandler.txt)

**Comment by jansenbe** [comment]
Thanks Pete, we'll have a look at this

**Comment by jansenbe** [comment]
Hi Pete,

After validating the code this issue is solved: we fixed this as part of the upcoming 1.1 release of the Partner pack
