### ISSUE TITLE
Azure Instructions out of date

### ISSUE THREAD

**Issue by Dean144** [OfficeDev/PnP-Partner-Pack#99]
The instructions explain how to use the old Azure Portal. Can these be update to explain what needs to be done in the new site at portal.azure.com

**Comment by PaoloPia** [comment]
Hi Dean,
Thanks for your feedback. Unfortunately most of the azure-related steps described in the PnP Partner Pack Setup Guide are not yet available in the "new" Azure Portal. In fact, portal.azure.com redirects to manage.windowsazure.com for managing Azure AD. We will update instructions, targeting the new Azure Portal, as soon as it will be possible.
Thanks.

**Comment by Dean144** [comment]
Thanks for the quick response. That explains why I couldn't do the necessary steps in the new portal

Dean
________________________________
